#!/usr/bin/python3
import sys

lines = sys.stdin.readlines()
l = []

lemma = sys.argv[1]
for line in lines:
    num = line.split(':')[0]

    if lemma == "T_Gossip_verif_empty":
        if "LoggerComputesAddLog(" in line:
            l.append(num)
        elif "InclusionProof(" in line:
            l = [num] + l
        elif "Gos_AppendOnlyCheck(" in line:
            l = [num] + l
        elif "LoggerPresentsView(" in line:
            l = [num] + l
        else:
            continue

    elif ((lemma == "A_CTExt_3_ca_rogue_logger_blamed_min")):
        if "(∃ idCA.1 stmt ca_fields ca_fields2 rootCA idM idL.1 idL1 idL2 sth    session #t0 #t1 #t2 #t3 #t4.   (CAFakesCert( idCA.1, stmt, ca_fields ) @ #t0) ∧   (DocumentedIntermediateCA( rootCA, ca_fields, idCA.1 ) @ #t1) ∧   (ClientAcceptsChain( idL1, idL2, rootCA, ca_fields2, idCA.1, stmt    ) @ #t2) ∧   (MonitorFetchesLogSnapshot( idM, idL.1, session ) @ #t3) ∧   (MonitorFindsCert( idM, idL.1, stmt, ca_fields, sth, session    ) @ #t4)  ∧   (((idL.1 = idL1) ∨ (idL.1 = idL2))) ∧   (∀ IdFetcher log_id time #t1.1.     (LoggerPresentsView( idL.1, IdFetcher, log_id, time, sth, session      ) @ #t1.1)    ⇒     ∀ #t0.1. (Time( time ) @ #t0.1) ⇒ ¬(#t0.1 < #t1.1)) ∧   (#t2 < #t3) ∧   (((idCA.1 = $idCA) ∨ (idCA.1 = $idL))) ∧   (((¬($idCA = idCA.1)) ∨ (¬($idL = idCA.1)))))  ∥ (∃ idCA.1 idL.1 stmt ca_fields ca_fields2 rootCA idM idL1 idL2 sth    session #t0 #t1 #t2 #t3 #t4.   (CAFakesCert( idCA.1, stmt, ca_fields ) @ #t0) ∧" in line:
            l = [num] + l
        elif "($idCA.1 = $idCA)  ∥ ($idCA.1 = $idL)" in line:
            l = [num] + l
        elif "($idL.1 = $idL1.1)  ∥ ($idL.1 = $idL2.1)" in line:
            l = [num] + l
        elif "($idL.1 = $idCA)  ∥ ($idL.1 = $idL)" in line:
            l = [num] + l
        elif "!Logger( $idCA, pkL.1 ) ▶₃ #t4.1" in line:
            l = [num] + l
        elif "($idCA.1 = $idCA) ∥ ($idCA.1 = $idL)" in line:
            l = [num] + l
        elif "!CA_Documentation( $rootCA.2, $idCA,                   <$rootCA.2, $idCA, pk(x.7), 'pubKey-CA', snCA.2, $i0.2, $j0.2>,                   sign(<$rootCA.2, $idCA, pk(x.7), 'pubKey-CA', snCA.2, $i0.2, $j0.2                        >,                        x.9)) ▶₃ #t1.1" in line:
            l = [num] + l
        elif "!Logger( $idCA, pkL.1 ) ▶₂ #t3.1" in line:
            l = [num] + l
        elif "!CA_Documentation( $rootCA.3, $idL,                   <$rootCA.3, $idL, pk(x.7), 'pubKey-CA', snCA.2, $i0.2, $j0.2>,                   sign(<$rootCA.3, $idL, pk(x.7), 'pubKey-CA', snCA.2, $i0.2, $j0.2>,                        x.9)) ▶₃ #t1.1" in line:
            l = [num] + l
        elif "!Logger( $idL, pkL.1 ) ▶₂ #t3.1" in line:
            l = [num] + l
        elif "($rootCA.2 = $idCA)  ∥ ($rootCA.2 = $idL)" in line:
            l = [num] + l
        elif "!Root_CA( $idCA, pk(x.9) ) ▶₂ #t1.1" in line:
            l = [num] + l
        elif "!Root_CA( $idL" in line:
            l = [num] + l
        elif "!Logger( $idL," in line:
            l = [num] + l
        else:
            continue

    else:
        exit(0) # instead then use default heuristic (o or O)

    # Add custom behavior here for other lemmas here
    # elif lemma == "OTHER_LEMMA_NAME":
    #     if re.match('SOME_REGEX', line):
    #         l.append(num)
    #     else:
    #         exit(0)

for i in l:
    print(i)